Iter13
ujwegh/shortener pull request #13
Opened 2023-11-14 12:08 UTC by ujwegh

2023-11-17 18:40 UTC, capsulated requested changes
Все в принципе классно. Даже с контекстом вроде всё правильно.

❌ Но в части инициализации хранилки нужно создание соединения и миграции "спрятать" в конструктор DbStorage. И желательно вызывать абстракную фабрику для хранилки, которую описать внутри пакета storage, а не cmd

А в следующем спринте обязательно добавить негативные тест кейсы с таймаутом  контекста 😄

2023-11-17 18:40 UTC, capsulated commented on cmd/shortener/main.go
> -	s := storage.NewFileStorage(c.FileStoragePath)
❌ Нужно убрать условный оператор, чтобы не дублировать вызов  конструкторов сервиса, хендлеров и тп. 

Можно создать отдельную абстрактную фабрику в пакете `storage`, выходной параметр у которой будет описан интерфейсом:
```go
func NewStorage(cfg *config.Storage) (Storage, error) {
   if (...) {
      return NewDbStorage(...)
   }
   
   if (...) {
      return NewFileStorage(...)
   }
   
   return NewMemoryStorage...)
}
```

2023-11-17 18:40 UTC, capsulated commented on cmd/shortener/main.go
> +		db := storage.Open(c.DatabaseDSN)
❌ Открывать соединение к базе на уровде cmd - плохая затея.

Открытие соединения нужно убрать в конструктор `NewDBStorage(...)`. Конструкторы именно для инициализации объектов и сделаны. Это аналог  `def __init__(self)` в питоне или `constructor()` в typescript

2023-11-17 18:40 UTC, capsulated commented on cmd/shortener/main.go
> -func initLogger(level string) {
👍 Вот логгер как раз "переехал" в свой пакет, где и должен быть))))

2023-11-17 18:40 UTC, capsulated commented on internal/app/handlers/handlers.go
> +			if err != nil {
Большое ветвление if/else получилось, по возможности нужно максимально упрощать

2023-11-17 18:40 UTC, capsulated commented on internal/app/handlers/handlers.go
> +		contextTimeout:   time.Duration(contextTimeout) * time.Second,
Хммм, в задании вроде не было таймаутов для запросов 🤔. Но реализовано на первый взгляд, вроде правильно

2023-11-17 18:40 UTC, capsulated commented on internal/app/handlers/handlers.go
> +			errMsg, errCode = "Request canceled", http.StatusInternalServerError
Раз проявлена инициатива, тогда доожны быть кейсы в тестах с `Request canceled` и `Timeout exceeded` в следующем спринте 😄

2023-11-19 12:23 UTC, ujwegh commented on cmd/shortener/main.go
> -	s := storage.NewFileStorage(c.FileStoragePath)
поправил

2023-11-19 12:37 UTC, ujwegh commented on cmd/shortener/main.go
> +		db := storage.Open(c.DatabaseDSN)
поправил, но кажется неверно сделал) это странно получается, по мне так DbStorage не должен быть ответственнен за создание соединения с базой и выполнение миграций. На примере DataSource в java - его никто не создает на уровне имплементации сервиса для взаимодействия с бд, он должен быть создан и настроен при старте приложения на уровне конфигурации и заинжекчен в наш сервис работы с репозиторием. но это джавовый подход конечно)

2023-11-19 12:48 UTC, ujwegh commented on internal/app/handlers/handlers.go
> +			if err != nil {
подрефачил

2023-11-19 12:48 UTC, ujwegh commented on internal/app/handlers/handlers.go
> +			errMsg, errCode = "Request canceled", http.StatusInternalServerError
ок

2023-11-19 12:54 UTC, ujwegh commented on cmd/shortener/main.go
> -	s := storage.NewFileStorage(c.FileStoragePath)
правда совсем неясно почему он должен уметь возвращать ошибку - по мне так если он не смог инициализировать ничего, то он должен сам panic кинуть

2023-11-20 13:12 UTC, capsulated commented on cmd/shortener/main.go
> -	s := storage.NewFileStorage(c.FileStoragePath)
Это для примера. Если ошибок нет, а только паника - то конечно не надо. Все имена, параметры входные и выходные, а также количество конструкторов может быть другое.

2023-11-20 13:20 UTC, capsulated reviewed
Всё супер 👍

2023-11-20 13:20 UTC, capsulated approved these changes
Всё супер 👍

2023-11-20 13:22 UTC, merged