Iter9
ujwegh/shortener pull request #9
Opened 2023-11-01 20:43 UTC by ujwegh

2023-11-01 21:26 UTC, ujwegh commented on internal/app/storage/filestorage.go
> +	file, err := os.OpenFile(filename, os.O_RDONLY|os.O_CREATE, 0666)
неясно почему не проходит тест - Error:      	unable to find file "/tmp/ROxgUCd" - ведь флаги стоят на автосоздание файла

2023-11-06 14:26 UTC, capsulated requested changes
В общем, всё хорошо, но есть небольше замечание: не "прибивать гвоздями" логгер к middleware: инициализировать логгер, а затем передать его в middleware. Подробнее - в коментах

2023-11-06 14:26 UTC, capsulated commented on internal/app/config/config.go
> +	err := middlware.LoggerInitialize(logLevel)
❌ Это должно быть отдельно от инициализации логгера. Сначала инициализируем логгер, а затем, независимо, инициализируем middleware. Кейс: если нужно отключить middleware логирования (скажем, новый флаг конфига), на инициализацию логгера это не должно влиять.

В идеале: отдельный пакет для логгера. И отдельные объекты middleware, можно в пакете хендлера, а можно и в новом пакете, как реализовано в [chi](https://github.com/go-chi/chi/tree/master/middleware) (хороший пример)

2023-11-06 14:26 UTC, capsulated commented on internal/app/middlware/logger.go
> +func LoggerInitialize(level string) error {
❌ Отдельный логгер инициализировать для middleware скорее лишнее,  так как в рамках приложения стиль логгера почти всегда одинаковый. Его нужно инициализировать на уровне `cmd`, а в middleware передать зависимость на логгер (передать экземпляр по указателю или использовать глобальный экземпляр логгера)

2023-11-06 14:26 UTC, capsulated commented on internal/app/model/dtos.go
> +package model
В go обычно не выделяют отдельный model (хотя, конечно, можно реализовать как MVC, так и DDD c Entity/UseCase), но обычно удобнее определять объекты там, где используются, так же, как и интерфейсы. 

То есть, `ShortenRequest` и `ShortenResponse` - это объекты handler'а, а `ShortenedURL`  - это, скорее всего, должен быть специальный пакет-воркер, который создаёт короткие ссылки.

Это больше рекомендация - разные подходы к созданию структуры приложения

2023-11-07 12:37 UTC, capsulated requested changes
Написал комментарии, критикал отмечены крестиком.

Самое главное замечание: в пакете logger так и остался функционал middleware. Его просто нужно скопиастить в middleware (или отдельные пактеы)

PS (С этим всё ок, просто комментарий) В принципе, сами объекты `compressWriter`, `compressReader`, `responseRecorder` могут быть и в независимых пакетах - это тоже вполне ок. Функции middleware формата `func MyMiddleware(next http.Handler) http.Handler` могут быть в middleware, handler, router - так как по функционалу относятся к ним. 

В общем, код вполне хороший, но момент с зависимостями (структура объектов программы) очень важный: какие объекты от каких зависят, какая структура использует методы другой структуры (зависимость - Dependency)

2023-11-07 12:37 UTC, capsulated commented on internal/app/logger/logger.go
> +type responseRecorder struct {
❌ Этот объект относиться либо к middleware, либо к handler, в пакете логгера его быть не должно. Просто можно перенести туда вместе с методами. Логгер ничего не должен "знать" про респонсы, статусы и тп - это логика хендлеров

2023-11-07 12:37 UTC, capsulated commented on internal/app/logger/logger.go
> +func RequestLogger(next http.Handler) http.Handler {
❌ Эту функцию, также, как zipper, просто перетащить в папку (пакет) middleware, можно отдельным файлом middleware/logger.go

2023-11-07 12:37 UTC, capsulated commented on internal/app/logger/logger.go
> +func ResponseLogger(next http.Handler) http.Handler {
❌ Эту функцию, также, как zipper, просто перетащить в папку (пакет) middleware, можно отдельным файлом middleware/logger.go

2023-11-07 12:37 UTC, capsulated commented on internal/app/logger/logger.go
> +func getResponseBodyForLogging(body []byte) string {
❌ Эту функцию, также, как zipper, просто перетащить в папку (пакет) middleware, можно отдельным файлом middleware/logger.go

PS Можно в функцию и не оборачивать, это уже даже перебор. Можно несколько разных middleware сделать, так даже лучше было бы. 

`middleware.RequestLogging`
`middleware.ResponseLogging`

2023-11-07 12:37 UTC, capsulated commented on internal/app/model/dtos.go
> +package model
❌ Тут либо нужно перенести типы в другие пакеты, либо в комментарии что-то ответить. В данном случае это не ошибка, а другой подход, но его надо обязательно обосновать, почему такое решение выбрано

2023-11-07 12:37 UTC, capsulated commented on internal/app/router/router.go
> +	r.Use(logger.RequestLogger)
❌ Вот тут должно `middlware.ResponseLogger` и `middlware.ResponseLogger`. Сам пакет логгера тут учавствовать не должен. Так как пакет middleware зависит от logger, а пакет logger **не должен** зависеть от middleware

2023-11-07 19:29 UTC, ujwegh commented on internal/app/config/config.go
> +	err := middlware.LoggerInitialize(logLevel)
поправил

2023-11-07 19:29 UTC, ujwegh commented on internal/app/middlware/logger.go
> +func LoggerInitialize(level string) error {
поправил

2023-11-07 20:14 UTC, ujwegh commented on internal/app/logger/logger.go
> +type responseRecorder struct {
поправил

2023-11-07 20:14 UTC, ujwegh commented on internal/app/logger/logger.go
> +func RequestLogger(next http.Handler) http.Handler {
поправил

2023-11-07 20:14 UTC, ujwegh commented on internal/app/logger/logger.go
> +func ResponseLogger(next http.Handler) http.Handler {
поправил

2023-11-07 20:15 UTC, ujwegh commented on internal/app/logger/logger.go
> +func getResponseBodyForLogging(body []byte) string {
поправил

2023-11-07 20:15 UTC, ujwegh commented on internal/app/router/router.go
> +	r.Use(logger.RequestLogger)
поправил

2023-11-08 08:26 UTC, ujwegh commented on internal/app/model/dtos.go
> +package model
вообще сделал так из-за нескольких причин,
1) главная цель обезопасить себя от проблемы когда go запрещает внедрять циклические зависимости, а с учетом того что  ShortenedURL много где используется  придется плодить каждый раз внутренние типы, и маппить сущности каждый раз при вызове внутренних сервисов (на мой взгляд это оверхед), но конечно я не сильно еще разобрался в подходах в го и нет понимания как лучше)
2) проект маленький хранить все дтошки в одном месте удобно
3) для такого проекта подошел бы mvc вполне

поправил частично
согласен, ShortenRequest и ShortenResponse - это объекты handler'а, перенес туда

2023-11-08 10:21 UTC, capsulated approved these changes
Всё супер

2023-11-08 10:21 UTC, capsulated commented on cmd/shortener/main.go
> +func initLogger(level string) {
Это же как раз можно было в пакет `internal/logger` убрать

2023-11-08 16:51 UTC, merged